<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            // Shirts
            [
                'category_id' => 1,
                'name' => 'Premium White Formal Shirt',
                'slug' => 'premium-white-formal-shirt',
                'description' => 'Elegant white formal shirt made from premium cotton. Perfect for business meetings and formal events. Features a crisp collar, mother-of-pearl buttons, and a professional fit.',
                'short_description' => 'Elegant white formal shirt for business and formal wear',
                'price' => 2500,
                'discount_price' => 1999,
                'sku' => 'SHIRT-001',
                'stock_quantity' => 50,
                'color' => 'White',
                'available_colors' => json_encode(['White', 'Off-White']),
                'material' => '100% Cotton',
                'fabric_type' => 'Premium Cotton',
                'size' => 'M',
                'available_sizes' => json_encode(['S', 'M', 'L', 'XL', 'XXL']),
                'is_active' => true,
            ],
            [
                'category_id' => 1,
                'name' => 'Sky Blue Casual Shirt',
                'slug' => 'sky-blue-casual-shirt',
                'description' => 'Comfortable casual shirt in sky blue. Perfect for everyday wear and semi-formal occasions. Featuring a relaxed fit and breathable fabric.',
                'short_description' => 'Comfortable casual shirt in sky blue',
                'price' => 1800,
                'discount_price' => 1399,
                'sku' => 'SHIRT-002',
                'stock_quantity' => 40,
                'color' => 'Sky Blue',
                'available_colors' => json_encode(['Sky Blue', 'Light Blue', 'White']),
                'material' => '100% Cotton',
                'fabric_type' => 'Breathable Cotton',
                'size' => 'M',
                'available_sizes' => json_encode(['S', 'M', 'L', 'XL']),
                'is_active' => true,
            ],
            [
                'category_id' => 1,
                'name' => 'Black Linen Shirt',
                'slug' => 'black-linen-shirt',
                'description' => 'Premium black linen shirt. Breathable and elegant, perfect for summer formal events. Made from pure linen for maximum comfort.',
                'short_description' => 'Premium black linen shirt, breathable and elegant',
                'price' => 3000,
                'discount_price' => 2399,
                'sku' => 'SHIRT-003',
                'stock_quantity' => 30,
                'color' => 'Black',
                'available_colors' => json_encode(['Black', 'Navy', 'Beige']),
                'material' => '100% Linen',
                'fabric_type' => 'Pure Linen',
                'size' => 'M',
                'available_sizes' => json_encode(['M', 'L', 'XL']),
                'is_active' => true,
            ],

            // Pants
            [
                'category_id' => 2,
                'name' => 'Black Formal Trousers',
                'slug' => 'black-formal-trousers',
                'description' => 'Sophisticated black formal trousers. Ideal for business and formal events. Features a tailored fit with pleated front and premium wool blend.',
                'short_description' => 'Sophisticated black formal trousers for formal occasions',
                'price' => 3500,
                'discount_price' => 2799,
                'sku' => 'PANTS-001',
                'stock_quantity' => 45,
                'color' => 'Black',
                'available_colors' => json_encode(['Black', 'Charcoal']),
                'material' => 'Wool Blend',
                'fabric_type' => 'Wool Blend 65/35',
                'size' => '32',
                'available_sizes' => json_encode(['28', '30', '32', '34', '36']),
                'is_active' => true,
            ],
            [
                'category_id' => 2,
                'name' => 'Navy Chinos',
                'slug' => 'navy-chinos',
                'description' => 'Casual navy chino pants. Great for smart casual occasions. Comfortable and durable with a modern fit.',
                'short_description' => 'Casual navy chino pants for smart casual wear',
                'price' => 2200,
                'discount_price' => 1699,
                'sku' => 'PANTS-002',
                'stock_quantity' => 35,
                'color' => 'Navy',
                'available_colors' => json_encode(['Navy', 'Khaki', 'Olive']),
                'material' => '98% Cotton, 2% Elastane',
                'fabric_type' => 'Cotton Stretch',
                'size' => '32',
                'available_sizes' => json_encode(['30', '32', '34', '36']),
                'is_active' => true,
            ],

            // Kurtas
            [
                'category_id' => 3,
                'name' => 'Cream Traditional Kurta',
                'slug' => 'cream-traditional-kurta',
                'description' => 'Traditional cream kurta made from premium cotton. Perfect for cultural events and festivals. Features traditional embroidery and authentic design.',
                'short_description' => 'Traditional cream kurta for cultural events',
                'price' => 2800,
                'discount_price' => 2199,
                'sku' => 'KURTA-001',
                'stock_quantity' => 25,
                'color' => 'Cream',
                'available_colors' => json_encode(['Cream', 'Beige', 'White']),
                'material' => '100% Cotton',
                'fabric_type' => 'Premium Cotton',
                'size' => 'L',
                'available_sizes' => json_encode(['S', 'M', 'L', 'XL', 'XXL']),
                'is_active' => true,
            ],
            [
                'category_id' => 3,
                'name' => 'Black Silk Kurta',
                'slug' => 'black-silk-kurta',
                'description' => 'Luxurious black silk kurta. Ideal for special occasions and celebrations. Premium quality silk with elegant drape.',
                'short_description' => 'Luxurious black silk kurta for special occasions',
                'price' => 4500,
                'discount_price' => 3499,
                'sku' => 'KURTA-002',
                'stock_quantity' => 15,
                'color' => 'Black',
                'available_colors' => json_encode(['Black', 'Maroon', 'Navy']),
                'material' => '100% Silk',
                'fabric_type' => 'Pure Silk',
                'size' => 'L',
                'available_sizes' => json_encode(['M', 'L', 'XL']),
                'is_active' => true,
            ],

            // Blazers
            [
                'category_id' => 4,
                'name' => 'Navy Blue Blazer',
                'slug' => 'navy-blue-blazer',
                'description' => 'Classic navy blue blazer. Versatile for business and casual occasions. Premium wool blend with perfect tailoring.',
                'short_description' => 'Classic navy blue blazer for business and casual',
                'price' => 5500,
                'discount_price' => 4299,
                'sku' => 'BLAZER-001',
                'stock_quantity' => 20,
                'color' => 'Navy',
                'available_colors' => json_encode(['Navy', 'Black', 'Charcoal']),
                'material' => 'Wool Blend',
                'fabric_type' => 'Premium Wool Blend',
                'size' => '40',
                'available_sizes' => json_encode(['38', '40', '42', '44']),
                'is_active' => true,
            ],
            [
                'category_id' => 4,
                'name' => 'Black Formal Blazer',
                'slug' => 'black-formal-blazer',
                'description' => 'Elegant black formal blazer. Perfect for black tie events and formal occasions. Made from premium wool.',
                'short_description' => 'Elegant black formal blazer for black tie events',
                'price' => 6000,
                'discount_price' => 4699,
                'sku' => 'BLAZER-002',
                'stock_quantity' => 18,
                'color' => 'Black',
                'available_colors' => json_encode(['Black']),
                'material' => 'Wool',
                'fabric_type' => 'Premium Wool',
                'size' => '40',
                'available_sizes' => json_encode(['38', '40', '42', '44', '46']),
                'is_active' => true,
            ],

            // Suits
            [
                'category_id' => 5,
                'name' => 'Black 3-Piece Suit',
                'slug' => 'black-3-piece-suit',
                'description' => 'Premium 3-piece suit including blazer, trousers, and vest. Perfect for formal occasions and corporate events. Handcrafted tailoring.',
                'short_description' => 'Premium 3-piece black suit for formal occasions',
                'price' => 15000,
                'discount_price' => 11999,
                'sku' => 'SUIT-001',
                'stock_quantity' => 10,
                'color' => 'Black',
                'available_colors' => json_encode(['Black']),
                'material' => 'Wool',
                'fabric_type' => 'Premium Wool',
                'size' => '40',
                'available_sizes' => json_encode(['38', '40', '42', '44']),
                'is_active' => true,
            ],
            [
                'category_id' => 5,
                'name' => 'Navy Blue 3-Piece Suit',
                'slug' => 'navy-blue-3-piece-suit',
                'description' => 'Sophisticated navy blue 3-piece suit. Ideal for corporate and formal occasions. Includes blazer, trousers, and vest.',
                'short_description' => 'Sophisticated navy 3-piece suit for corporate events',
                'price' => 14500,
                'discount_price' => 11499,
                'sku' => 'SUIT-002',
                'stock_quantity' => 12,
                'color' => 'Navy',
                'available_colors' => json_encode(['Navy', 'Charcoal']),
                'material' => 'Wool Blend',
                'fabric_type' => 'Premium Wool Blend',
                'size' => '40',
                'available_sizes' => json_encode(['38', '40', '42', '44', '46']),
                'is_active' => true,
            ],

            // Waistcoats
            [
                'category_id' => 6,
                'name' => 'Black Formal Waistcoat',
                'slug' => 'black-formal-waistcoat',
                'description' => 'Classic black formal waistcoat. Perfect complement to any suit. Premium quality with perfect tailoring.',
                'short_description' => 'Classic black formal waistcoat for suits',
                'price' => 2500,
                'discount_price' => 1999,
                'sku' => 'VEST-001',
                'stock_quantity' => 22,
                'color' => 'Black',
                'available_colors' => json_encode(['Black', 'Charcoal']),
                'material' => 'Wool Blend',
                'fabric_type' => 'Wool Blend',
                'size' => '40',
                'available_sizes' => json_encode(['38', '40', '42', '44']),
                'is_active' => true,
            ],
            [
                'category_id' => 6,
                'name' => 'Maroon Waistcoat',
                'slug' => 'maroon-waistcoat',
                'description' => 'Elegant maroon waistcoat with gold accents. Perfect for weddings and formal events.',
                'short_description' => 'Elegant maroon waistcoat with gold accents',
                'price' => 2800,
                'discount_price' => 2199,
                'sku' => 'VEST-002',
                'stock_quantity' => 16,
                'color' => 'Maroon',
                'available_colors' => json_encode(['Maroon', 'Burgundy', 'Wine']),
                'material' => 'Wool',
                'fabric_type' => 'Premium Wool',
                'size' => '40',
                'available_sizes' => json_encode(['38', '40', '42']),
                'is_active' => true,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
